#!/bin/bash

TEST_PATH="$(cd "$(dirname "$0")" && pwd)"
REPO_PATH="${TEST_PATH}/repos"

function die ( ) {
   echo $@
   exit 1
}

# Color Vars
bldblk='\e[1;30m' # Black - Bold
bldred='\e[1;31m' # Red
bldgrn='\e[1;32m' # Green
bldylw='\e[1;33m' # Yellow
bldblu='\e[1;34m' # Blue
bldpur='\e[1;35m' # Purple
bldcyn='\e[1;36m' # Cyan
bldwht='\e[1;37m' # White
txtrst='\e[0m'    # Text Reset

echo -e "${bldgrn}===>${bldwht} Preparing testRepo...${txtrst}"

rm -rf ${REPO_PATH}/testRepo

cp -r ${REPO_PATH}/TEST_TEMPLATE ${REPO_PATH}/testRepo

echo -e "${bldwht}Done${txtrst}"
echo

echo -e "${bldwht}Would you like to run the update-repo tool on the testRepo?${txtrst}"
read -p "Continue (Y/n)? "
[ "${REPLY,,}" == y ] || [ "$REPLY" == '' ] || die "Exiting..."

echo
echo -e "${bldgrn}===>${bldwht} Running update-repo on testRepo....${txtrst}"
echo

${TEST_PATH}/update-repo testRepo

echo
echo -e "${bldwht}Would you like to check the results of update-repo testRepo?${txtrst}"
read -p "Continue (Y/n)? "
[ "${REPLY,,}" == y ] || [ "$REPLY" == '' ] || die "Exiting..."
echo
echo -e "${bldwht}Done${txtrst}"
